import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Aspects } from "@/components/aspects";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " pile overflow-hidden"}>
        <section>{children}</section>
        <section className="w-full h-full z-20 bg-slate-900 transition-transform duration-300 ease-in-out translate-y-[92lvh] has-[:checked]:translate-y-[15lvh] rounded-t-3xl">
          <Aspects />
        </section>
      </body>
    </html>
  );
}
