export const celestials = [
  {
    name: "earth",
    size: 0.34,
    distance: 0,
    angle: 0,
    texture: "/celestials/earth.jpg",
  },
  {
    name: "mars",
    size: 0.29,
    distance: 2.65,
    angle: Math.PI / 1.9,
    texture: "/celestials/mars.jpg",
  },
  {
    name: "jupiter",
    size: 0.38,
    distance: 2.65,
    angle: Math.PI / 1.24,
    texture: "/celestials/jupiter.jpg",
  },
  {
    name: "saturn",
    size: 0.28,
    distance: 2.2,
    angle: Math.PI / 1.07,
    texture: "/celestials/saturn.jpg",
  },
  {
    name: "pluto",
    size: 0.24,
    distance: 2.5,
    angle: Math.PI / 0.9,
    texture: "/celestials/pluto.jpg",
  },
  {
    name: "neptune",
    size: 0.27,
    distance: 2.1,
    angle: Math.PI * 1.34,
    texture: "/celestials/neptune.jpg",
  },
  {
    name: "uranus",
    size: 0.29,
    distance: 2.8,
    angle: Math.PI * 1.37,
    texture: "/celestials/uranus.jpg",
  },
  {
    name: "chiron",
    size: 0.19,
    distance: 2.6,
    angle: Math.PI * 1.53,
    texture: "/celestials/chiron.jpg",
  },
  {
    name: "moon",
    size: 0.21,
    distance: 2.8,
    angle: Math.PI * 1.63,
    texture: "/celestials/moon.jpg",
  },
  {
    name: "lilith",
    size: 0.19,
    distance: 2.1,
    angle: Math.PI * 1.72,
    texture: "/celestials/lilith.jpg",
  },
  {
    name: "north_node",
    size: 0.195,
    distance: 1.9,
    angle: Math.PI * 1.8,
    texture: "/celestials/north_node.jpg",
  },
  {
    name: "mercury",
    size: 0.24,
    distance: 2.2,
    angle: Math.PI * 1.95,
    texture: "/celestials/mercury.jpg",
  },
  {
    name: "venus",
    size: 0.26,
    distance: 2.1,
    angle: Math.PI * 2.1,
    texture: "/celestials/venus.jpg",
  },
  {
    name: "sun",
    size: 0.4,
    distance: 2.7,
    angle: Math.PI * 2.34,
    texture: "/celestials/sun.jpg",
  },
];
